{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "httpbin.fullname" . }}
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "httpbin.selectorLabels" . | nindent 4 }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      {{- with .Values.hosts }}
      hosts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
